services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $rules: !tagged_iterator app.loan_rules
            $modifiers: !tagged_iterator app.loan_rate_modifier

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # Auto-tag all loan rules
    App\Service\LoanRules\:
        resource: '../src/Service/LoanRules'
        tags: ['app.loan_rules']

    # ✅ Auto-tag all LoanRateModifierInterface implementations in LoanRate
    App\Service\LoanRate\:
        resource: '../src/Service/LoanRate'
        tags: ['app.loan_rate_modifier']

    App\EventListener\LoanCreatedListener:
        tags:
            - { name: kernel.event_listener, event: App\Event\LoanCreatedEvent }
